# einfo
POST {{host}}/einfo.fcgi
Content-Type: application/x-www-form-urlencoded
Accept: application/json

db=protein&version=2.0&retmode=json&api_key={{api_key}}&email={{email}}&tool={{tool}}

###

# esearch
POST {{host}}/esearch.fcgi
Content-Type: application/x-www-form-urlencoded
Accept: application/json

db=protein&term=("ribonuclease t2"[title] AND "RNase"[title])&idtype=acc&rettype=uilist&retmode=json&usehistory=&retstart=0&retmax=10&api_key={{api_key}}&email={{email}}&tool={{tool}}

###

# epost
POST {{host}}/epost.fcgi
Content-Type: application/x-www-form-urlencoded
Accept: application/xml

db=nuccore&id=1746590493&api_key={{api_key}}&email={{email}}&tool={{tool}}

###

# efetch
POST {{host}}/efetch.fcgi
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

#db=protein&rettype=acc&retmode=text&query_key=1&retstart=0&retmax=250&WebEnv=NCID_1_71904942_130.14.18.97_9001_1585468777_812288825_0MetA0_S_MegaStore&api_key={{api_key}}&email={{email}}&tool={{tool}}
#download specific part of the sequence
#db=nuccore&id=BKCP01000669.1&rettype=fasta&retmode=text&location=240994:241150:2,240845:240918:2&api_key={{api_key}}&email={{email}}&tool={{tool}}
#db=nuccore&id=BKCP01000669.1&rettype=fasta&retmode=text&location=240994:241150:2,240845:240918:2,239967:240217:2,239735:239875:2,239255:239456:2&api_key={{api_key}}&email={{email}}&tool={{tool}}

db=nuccore&id=BKCP01000669.1&rettype=fasta&retmode=text&location=780916:781155,781187:781249&api_key={{api_key}}&email={{email}}&tool={{tool}}

###

# elink
POST {{host}}/elink.fcgi
Content-Type: application/x-www-form-urlencoded
Accept: application/json
#cmd=neighbor&dbfrom=protein&db=nuccore&retmode=json&idtype=acc&query_key=1&WebEnv=NCID_1_71904942_130.14.18.97_9001_1585468777_812288825_0MetA0_S_MegaStore&api_key={{api_key}}&email={{email}}&tool={{tool}}
#id=153424&cmd=acheck&dbfrom=protein&retmode=json&idtype=acc&api_key={{api_key}}&email={{email}}&tool={{tool}}
#id=GER25982.1&cmd=neighbor&dbfrom=protein&db=nuccore&linkname=protein_nuccore&retmode=json&idtype=acc&api_key={{api_key}}&email={{email}}&tool={{tool}}
#protein_taxonomy

id=GER25982.1&cmd=neighbor&dbfrom=protein&db=taxonomy&linkname=protein_taxonomy&retmode=json&idtype=acc&api_key={{api_key}}&email={{email}}&tool={{tool}}

###

# espell
POST {{host}}/espell.fcgi
Content-Type: application/x-www-form-urlencoded
Accept: application/xml

db=taxonomy&term=arabidopis

###
