*** Settings ***
Library   kakapo.orf

*** Variables ***
@{start_codons_1}  ATG
@{start_codons_2}  TTG  CTG  ATG
@{stop_codons}     TAA  TAG  TGA

${seq1}            GAAGAAGTGGTGGAGGAGTATGAGGAGGAGGTGGAAGAAGAGGAGGCAGTTGAAGAGACCGTGCAGGAAGAAGACGGACCTGCTGCAGAGGAGGAGGCCGGTGAAGAACAAGATGGAGAAGAGGAAGCCGAAGAAGGAGAAGAGGAGGAAACCAAACCAAAATTCAAGCCATTTATCATGCCAAACCTCATCCCTCCCAAGATCCCAGATGGAGAGAAGGTGGATTTTGATGATATACATCGTAAAAGGATGGAGAAGGATCTGATGGAGCTTCAGACTTTGATTGAGGTTCACTTTGAGAGCAGAAAGAAGGAAGAAGAGGAGCTCATTCATCTCAAAGAGAGGATTGAGAAGCGCCGGTTTGAGCGAGCAGAGCAACATAGAATCCGCAGTGAGAGAGAGAAAGAGCGACAGAAGCGCCTTGAGGAGGAGAGAGCTCGTAAGGAGGAGGAAGAAGCCAAGAGGAGAGCAGAGGATGATGCTAAGAAGAAGAAAACCCTGACCAGCCTCCACTTTGGAGGGTACATGCAGAAACTGACAGAGAAACGGAGTGGTAAGAGGCAGACTGAGAGAGAGAAGAAGAAGAAGATCCTGAGTGACAGACGCAAATCTCTGGAAATTGAGCACTTGAGCCAGGAAAAGCTCAAGGAGAAAGCTAAGGAGCTTTGGGAGTGGATGTACCAGCTGGAGGCAGAGAAGTTTGAGCTGCAGTACCAGTTCACCAGACAGAAATATGAGATTAATGTGCTGAGGAATCGTGTCAGCGATCATCAGAAAACATCCAAGAGAACCAAGAGAGGCCTAAGGAAATAGATGCTGACATGCTGAGTGAGCAGTGTAATCATCAGCCCTGTCCTGGAGCTATAACCTGAGACCAAGTCCTGGCTTTCCAGCCACACCCCA
@{seq1_orf}        ${177}  ${813}

*** Test Cases ***
orf.find_longest_orfs 1
    @{x}  Find Longest Orfs
    ...    seq=${seq1}
    ...    frame=${1}
    ...    min_len=${3}
    ...    stop_codons=${stop_codons}
    ...    start_codons=${start_codons_1}
    ...    include_terminal_codon=True
    ...    ret_max=${1}
    @{seq1_orf}  Create List  ${seq1_orf}
    Should Be Equal  ${x}  ${seq1_orf}

orf.find_orf_for_blast_hit 1
    @{x}  Find Orf For Blast Hit
    ...    seq=${seq1}
    ...    frame=${1}
    ...    hit_start=${150}
    ...    hit_end=${792}
    ...    hit_length_adjust=${0}
    ...    stop_codons=${stop_codons}
    ...    start_codons=${start_codons_1}
    ...    include_terminal_codon=True
    Should Be Equal  ${x}  ${seq1_orf}
